### ISSUE TITLE
0.3.93 - Issues with activating train routes 

### ISSUE THREAD

**Issue by Nexela** [Choumiko/SmartTrains#32]
Using Siggboy's V2 map and mods with, 0.3.93 Smart Trains, 0.4.15 Fat Controller .12.35 Factorio

Some of these worked in .82 and not sure if the changes were intended or not.
To test any of these first create a test station before the depot and drop a loco and wagon on it.

(A) New train lines don't activate until you send it to a station on the smart route
Open Train Gui, activate siggboy's route in ST Gui, close train gui and reopen. Route doesn't update. in .82 the route would update right away. (you could open a new train click run and then activate it. when you closed the train gui the train would take off).  

(B) Trains at a station not on the route don't update but flying text shows it is "waiting" on the rules.
Open Train gui, add test station and run, when you get to the station check active on the ST route, Stop and Run the train. Close train gui. Text will show it is waiting for rules at the test station (pretty sure this is not intended). Route is not updated in GUI when reopening. At one point I am certain I had seen something about the station not being part of the route so not updating flying text

B ties into A for me.  I would send all my extra trains to a waiting a station and all I would have to do to add it to a route was active the route in smart trains and remove the waiting station in the train gui. The changed behavior means I have to add the depot station and send it.

If these were intended changes that's ok too :)

Can't wait for .13 and the magic from Smart Trains and Siggboy's Smart Routes. This is my must have mod.

**Comment by Choumiko** [comment]
None of these where intended :)
A is fixed in the version I forgot to push before leaving for work yesterday..
B sounds unrelated to A from your description. In theory trains shouldn't update on a station that wont be in the new schedule and therefore they should not wait for rules (unless the station is in the old schedule?!)
Updating lines is starting to become a real pain, since I want to prevent updating in situations that might lead to No Path errors.  I might have to rethink the current approach eventually.
Thanks for the verbose reports ;-)
