### ISSUE TITLE
[Minor] Auto Refuel not removing station after refueling.

### ISSUE THREAD

**Issue by GHXX** [Choumiko/SmartTrains#61]
# The issue
Since it's now time for me to set up a train-system i wanted to use the auto-refuel feature, but it seems that the refuel station gets added to the station-table in the train (below the Automatic-Manual switch), but it never gets removed.

# Notes
In the global settings i set:
go to refuel station below 200 (25coal). That works.
leave above 800 (100 Coal). a train can fit 150 coal max so that should be good too.
max refueltime 10. shouldnt matter
refuel station: "Refuel L". The refuel station is called the exact same. 
All my trains do go there, but once they were there and they got all their coal they keep going there because the station doesnt get removed from the train.
update interval is 60 ticks

If you need any more info, let me know!

**Edit: This issues seems to only apply if there is just one station in the train-timetable**

**Comment by Choumiko** [comment]
I check the schedule if there's more than 2 (>=3) stations in the schedule before removing the refuel station. I can't really remember the reason since that change is more than 2 years old.
I'm gonna keep it, since i can't think of a use for a train with only 1 stop in the schedule?

The reason might have been a "Refuel station refueling train" that goes from a coal mine to the refueling station(s) to fill up their coal? Don't know anymore

**Comment by GHXX** [comment]
Okay, makes sense to be honest, but it was confusing at first. Thanks for clarifying though!
